name:                autotuner
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Mathias & Simon"
maintainer:          ""
copyright:           ""

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Nothing here 

dependencies:
- base >= 4.7 && < 5
- array
- process
- containers
- regex-compat
- regex-base
- split

library:
  source-dirs: src

executables:
  autotuner-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autotuner

tests:
  autotuner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - autotuner
